language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: dwEuFoIkoVWStWlvL/U0P+shY+dwIKBQ7oB2DNS+9v+y5MquZhwTSRAuIhvIujbBxB2FtgG0jEX3lHwRCOpJfmxDEz44bOCcmv+RGZjhMqjWI4sPw0Z47JzYEPyS7rG45167WJ/cs3t/u97W96PcGFSvGJQHfx0hjshzS2lz0euVTyIkMKE7PO80iEVddmwMgZI4eA2HjqX5RXquk3v89PvF95n8Ba9+N8unOy0AYPhZr5On87vXjJ6372kPC3CALdTnnrzH23mOawPO+h60brWviYfKFWeS5jd4X/WAMv4EINMi0EmO0yOZ3NfbQ4Lc/JKu/jAHrs5EwQBYtIhi46J1TLCP824PTtkaNPw9qv/cQ+fYPVC9jsX5XuH0XbcWaHYZfkaREjNL9G0N48R2vtjp0QllJxZ8/+Z0jWnv67/nkIPSuXSbp+TtbdTJd5W1Da8eN1gBdQqHop2IEHZV85JSEIC7uy+pOdrX9xFwVyVdYuqwQbvwnQ475ygaLQuTcWMc74yIVwEXQLeV0AQcIuKKSZ/IORoBti40I0faydyCSfaQqse0cIW12J2mn9nmyxj1BBjg2krOXxoxGGaB60UW1K1bQDHIsOgy1m0ZeUi5nMX9NbdnjR1T7fBTc8Rgy0mc9P6MDgLYsBOQT7Qn/X389ipBK4AGlt+iH4gRS7E=
