# language: node_js
# node_js:
# - 10
# before_install:
# - npm install -g firebase-tools
# script:
# -
# deploy:
#   provider: firebase
#   skip_cleanup: true
#   on:
#     branch: master
#   token:
#     - $FIREBASE_TOKEN

language: ruby
rvm:
  - 2.2
before_install:
  - npm install
install: gem install jekyll
script:
-
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    - $FIREBASE_TOKEN
