language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    - 1/VP0skPC7gqOlO-nNC7skKBwQ2t-5y1XdeTV70fPNOMc
