language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  token:
    secure: "qwluVl58Y9+yDemmDiO39KV5KTa9BAEwYg3YGifDqceRiVmG/02M/phIKWPDXgBjxE+eEKovk/gQURQC3DsTsc3Go629KBKYZq39MzEpWK/ZklU7rKTBn4JoGBFCQ2CtiwxnOFYjk+1Ox8YqE+3JeriVe+3K9yzTPyUmiYSVOJBs/MCXUj59WaiNYR+ujD8A3BzGqbmW6sccijJrFhJkGQpUSqLAvMpJJd+urxnljLQihTrJiXGBgsYPss/vbD3mz2RIDWsb7mX4yWQaeqtfWoH4xgKXNsjRNtR1oLfdxSZLNeiUmFpLt7bn/EXv0/tOaXofDWpasvxKYQONUoJzAAzVR2hzbQoxeJtfgy6Fht3omH4oJmX2Cp5TKEENKmngacKqTzberN1FpMFyq2vjEMCw6a5NaAdZmFPWzgUQBbIQt/3U30BixKEapqXaoaN5Qmms9yPebXqgSMX5vKeaxcSZCqy77gwt5SwERCfwEWuCG8AeFwVnKFQFgm11AYv2CyIART5Cp+HLPVSzg0MF0GCeY6R7Wl1f+pBaE20KzU2nSTbxenKakbVZZw9HpVJ0w9Sc7jlBhWA0vWm8ZKneWwrYmYNKb+GiHR0CNeSdKMh4Tb0Nack3UI0cFf/ajLiZqHYTaTu9tKrbxS4LeTPq/TfKi7kwp/DkPDiIGvSNzDA="
# env:
#   global:
#     secure: qwluVl58Y9+yDemmDiO39KV5KTa9BAEwYg3YGifDqceRiVmG/02M/phIKWPDXgBjxE+eEKovk/gQURQC3DsTsc3Go629KBKYZq39MzEpWK/ZklU7rKTBn4JoGBFCQ2CtiwxnOFYjk+1Ox8YqE+3JeriVe+3K9yzTPyUmiYSVOJBs/MCXUj59WaiNYR+ujD8A3BzGqbmW6sccijJrFhJkGQpUSqLAvMpJJd+urxnljLQihTrJiXGBgsYPss/vbD3mz2RIDWsb7mX4yWQaeqtfWoH4xgKXNsjRNtR1oLfdxSZLNeiUmFpLt7bn/EXv0/tOaXofDWpasvxKYQONUoJzAAzVR2hzbQoxeJtfgy6Fht3omH4oJmX2Cp5TKEENKmngacKqTzberN1FpMFyq2vjEMCw6a5NaAdZmFPWzgUQBbIQt/3U30BixKEapqXaoaN5Qmms9yPebXqgSMX5vKeaxcSZCqy77gwt5SwERCfwEWuCG8AeFwVnKFQFgm11AYv2CyIART5Cp+HLPVSzg0MF0GCeY6R7Wl1f+pBaE20KzU2nSTbxenKakbVZZw9HpVJ0w9Sc7jlBhWA0vWm8ZKneWwrYmYNKb+GiHR0CNeSdKMh4Tb0Nack3UI0cFf/ajLiZqHYTaTu9tKrbxS4LeTPq/TfKi7kwp/DkPDiIGvSNzDA=
