language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: fdqSiz9u/nJ0JVNPRxvti669DyDlmFtk4bTHYD+GzGKHl++8EnyRpcEnYVhvT45U8rdeHBTBHmeea65585No5AiH06AAMxBzkSOHo68NPm0PcOQqOQUYL6YxojzGyRN4VxpML2LFqyz5KXkQQC8MZctXXtKcrOC8XjfFA6xGZumlbt+wedUYaGh2e7ryTeO4VjkBGj5zz6wXYlXdJFzQSF4OmKiNuzNRACqpJy1iJOS2i/LmpGvdEKlklGwZ4hk2Q1pMqCTh00I6yAPzPpeXM6l7jHJn9OF4NoIcBkge7EFarxpaH5g/+S80v2D3b74F+ZHeXLav9ZPJy7i4669Hs4bcmOnmKErRIlysqoHfhETVPGNEJS7HYz5GJINq9Whsi7LwixMn06EnXQFd8hV/EsYFHLQgYE27tNAnEIjHHMjSUnflF7VFO7Ok2qevRPLYhw9KYVGO999lRvESijbd4+fBcRIwC5p8+1h5vaksGMSQJm1GeVOb9cUgzUb3AVZSmj1b/XrQu/y1hJF53Pz/wtYpbjXF8Nk2g0GtI6mQTE2T915p4imMMtD2JfvisYpGno7kmZ9Of5sWh349XdpwI7IdXlnKuYfLk4kh6E5v2HO84GZHdddpn7smpxNb+T890Ks8HscUZIjQ+JG+mouBh9R4UHPX6s1Y6+18hL9wxik=
