language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: ZOodEagHQ5hBE/sFUuQ/D5jQWfXvt/eQxjYVncl32No7gw8gy7ywN+hLyYJlRx5OXqf1b+8Epiphs5AJJ5/m0w5W2gUekS5VjhxRTI0VXeoxzGk7xsEgAjDVtgfe+9K964/9ikzeY8HG+u6ux/wBBVSvTGDhmGvrAA4AmRndDZc/kKLwJSTiSvha/e9P5DnNtKPlOBncQE4Lb8e6VhYtHRIHT/LSLD1f3+zMfPezWyE6ZF6NpLH5vIDGn0PX0um1E7wx7FeSAIeVygeJcNGTBmO67pvnmjftAfwOAwng5iCf/QG8QGAmHLz8RWFuKWOUsemQeOvzLIFdWocuzCqasID88rVqLTkK5qAJ1sckm6pLrEH9tumOZ5y9niqgartnVEAF9RSI5Dr9D1k9NT56NkIirf9VwQWuzjK428sK31bR6WiDxFM300+WCgkNK0xQp7hZY4RNB9HsTteSbR8OktV3M5jRM82bYf5vjhZiG3/ziEMy+F8p2YSGV9CxCg4KYmbibzhXWzK9ki6z0ltucd+u/avSMBqi1eVZts8zGvRVWOpCjIEjuC1GICLr+loGlLoos7kl07mitwM/1tD3ijzDLwPQui9wpqhVW/tVaA8uqTbNrPkl2vqhppKr64iL1XhitNHoaFFcvB3jesRIgHRWtl6xu8mtWjLFF9h+25g=
