language: node_js
node_js:
- 10
before_install:
- npm install -g firebase-tools
script:
-
deploy:
  provider: firebase
  token:
    secure: "NCXZgnagKIHBI/cijWjyiVFQAeZf+1knuVrsqOaUq3eZ9ImuYM3ECBZb9KjeoE7wAieWCULZ6FxHAzZyahYW4f74MvRYKenrm5XKue1PUcTanJHZIF/nJvzn8RYlQrhQzjPVUpwGnq5lUKDG0k6kxQnSsIfwSEcImctU8TsZ0Q23UQV4WXghs509ldy7r8gh6+acns5oQeZfOgyhhpczyUqYvW0f19bA2zAEH0J9QiTSKvH+McR2j8NScKioG4hT5C5g63bu+GqtgLWBvhpNpuUpl8Zo6+Ta8p1nP54ddJluDiyFQP6N7kdOGgiJ4lgt6164G5W3ThqZsdKSS7jEjPPnhC3sc16EAlhexRowyUk5wjv2KHRFbPmWyVWKKjKTPPkL1RBJuB4Pv+k3r11zTBGOgUOfL3WburRtVLSid5B+/FlObD+DYoH4nzt33wX4jY5lj3DCF0VKGEFdK7FD3W28yqmVLd6ZktfAyozrNzdCNBL5aFH+3M6f2c2CNXa1FOLGECfgQOLfyWqcZ+oVhg54neprMG4bvJ9YLEZRhdWsaCAG55Pt3iqxr6PAeUy0s4AEgMLhFsg4/74cpvEOytZK0NKgt9UEOEiOi3je0AISApHbx9SRNpS9+1Mh7+2xlCetA08Ifhmr6TeO3lO5svjQdppY/2ZEb+ryHHyy4E8="
