# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Avery Vine
tagline:          'Blog'
description:      'A collection of posts about programming, music, travel, and my general life experiences'
url:              https://averyvine.com
baseurl:          '/blog'
source:           'public/_blog'
destination:      'public/blog'

author:
  name:           'Avery Vine'
  url:            https://twitter.com/AveryVine

paginate:         5
disqus:
  shortname: averyvine
excerpt_separator:  <!--more-->

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
# version:            3.7.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'
github:
  repo:             https://github.com/AveryVine

port: 5000

exclude: [vendor]
